name: Trigger Coolify Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Coolify webhook with Bearer token
        run: |
          curl -X POST \
               -H "Authorization: Bearer ${{ secrets.COOLIFY_BEARER_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{}' \
               ${{ secrets.COOLIFY_WEBHOOK_URL }}
